import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations11739372005676 implements MigrationInterface {
    name = 'Migrations11739372005676'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`FK_542fcdecad4a79dbee3bbe27250\` ON \`group_role_permission\``);
        await queryRunner.query(`DROP INDEX \`FK_83ebabf176958d675e0a73892be\` ON \`group_role_permission\``);
        await queryRunner.query(`DROP INDEX \`FK_275fe11db713fd6f9fd62709917\` ON \`bill\``);
        await queryRunner.query(`ALTER TABLE \`bill\` ADD \`expiration_time\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` CHANGE \`created_at\` \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` CHANGE \`groupRoleId\` \`groupRoleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` CHANGE \`permissionId\` \`permissionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`group_role\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`group_role\` CHANGE \`created_at\` \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bill\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket\` DROP FOREIGN KEY \`FK_2c35aa6c90c4dd7450dad753ae5\``);
        await queryRunner.query(`ALTER TABLE \`ticket\` DROP FOREIGN KEY \`FK_ab9b02f72bbc7d05bd15a5cb6b4\``);
        await queryRunner.query(`ALTER TABLE \`ticket\` DROP FOREIGN KEY \`FK_4931e2f03f0800846072cda2daf\``);
        await queryRunner.query(`DROP INDEX \`ticket_index\` ON \`ticket\``);
        await queryRunner.query(`ALTER TABLE \`ticket\` CHANGE \`showtimeId\` \`showtimeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket\` CHANGE \`seatId\` \`seatId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket\` CHANGE \`billId\` \`billId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`seat\` DROP FOREIGN KEY \`FK_1140d3d30847c3a13faa0a43329\``);
        await queryRunner.query(`ALTER TABLE \`seat\` CHANGE \`screenId\` \`screenId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`screen\` DROP FOREIGN KEY \`FK_251c9d2385c1ddcc67bb2e718e6\``);
        await queryRunner.query(`ALTER TABLE \`screen\` CHANGE \`theaterId\` \`theaterId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`showtime\` DROP FOREIGN KEY \`FK_1af27f8171269552599f8e18ff1\``);
        await queryRunner.query(`ALTER TABLE \`showtime\` DROP FOREIGN KEY \`FK_c723afd3a25e576a86d90c16d6f\``);
        await queryRunner.query(`DROP INDEX \`showtime_index\` ON \`showtime\``);
        await queryRunner.query(`ALTER TABLE \`showtime\` CHANGE \`movieId\` \`movieId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`showtime\` CHANGE \`screenId\` \`screenId\` int NULL`);
        await queryRunner.query(`DROP INDEX \`genre_full\` ON \`genre\``);
        await queryRunner.query(`ALTER TABLE \`genre\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` DROP FOREIGN KEY \`FK_f641f620b3fe496553aa442b026\``);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` DROP FOREIGN KEY \`FK_89ab58f5defce509fa9acffa723\``);
        await queryRunner.query(`DROP INDEX \`movieGenre_index\` ON \`movie_genre\``);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` CHANGE \`genreId\` \`genreId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` CHANGE \`movieId\` \`movieId\` int NULL`);
        await queryRunner.query(`DROP INDEX \`movie_text\` ON \`movie\``);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`trailerUrl\` \`trailerUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`posterUrl\` \`posterUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`releaseDate\` \`releaseDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`endDate\` \`endDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_1337f93918c70837d3cea105d39\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_4ccf71f9d14aa1a059877b06343\``);
        await queryRunner.query(`DROP INDEX \`review_index\` ON \`review\``);
        await queryRunner.query(`ALTER TABLE \`review\` CHANGE \`comment\` \`comment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` CHANGE \`movieId\` \`movieId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_88ff32ea732221f2c9ed3818908\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone\` \`phone\` varchar(15) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`created_at\` \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`groupRoleId\` \`groupRoleId\` int NULL`);
        await queryRunner.query(`CREATE INDEX \`bill_Index\` ON \`bill\` (\`orderCode\`, \`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`ticket_index\` ON \`ticket\` (\`showtimeId\`, \`seatId\`, \`billId\`)`);
        await queryRunner.query(`CREATE INDEX \`showtime_index\` ON \`showtime\` (\`movieId\`, \`screenId\`)`);
        await queryRunner.query(`CREATE FULLTEXT INDEX \`genre_full\` ON \`genre\` (\`name\`, \`description\`)`);
        await queryRunner.query(`CREATE INDEX \`movieGenre_index\` ON \`movie_genre\` (\`genreId\`, \`movieId\`)`);
        await queryRunner.query(`CREATE FULLTEXT INDEX \`movie_text\` ON \`movie\` (\`title\`, \`description\`)`);
        await queryRunner.query(`CREATE INDEX \`review_index\` ON \`review\` (\`rating\`, \`userId\`, \`movieId\`)`);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` ADD CONSTRAINT \`FK_542fcdecad4a79dbee3bbe27250\` FOREIGN KEY (\`groupRoleId\`) REFERENCES \`group_role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` ADD CONSTRAINT \`FK_83ebabf176958d675e0a73892be\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permission\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill\` ADD CONSTRAINT \`FK_275fe11db713fd6f9fd62709917\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ticket\` ADD CONSTRAINT \`FK_2c35aa6c90c4dd7450dad753ae5\` FOREIGN KEY (\`showtimeId\`) REFERENCES \`showtime\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ticket\` ADD CONSTRAINT \`FK_ab9b02f72bbc7d05bd15a5cb6b4\` FOREIGN KEY (\`seatId\`) REFERENCES \`seat\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ticket\` ADD CONSTRAINT \`FK_4931e2f03f0800846072cda2daf\` FOREIGN KEY (\`billId\`) REFERENCES \`bill\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seat\` ADD CONSTRAINT \`FK_1140d3d30847c3a13faa0a43329\` FOREIGN KEY (\`screenId\`) REFERENCES \`screen\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`screen\` ADD CONSTRAINT \`FK_251c9d2385c1ddcc67bb2e718e6\` FOREIGN KEY (\`theaterId\`) REFERENCES \`theater\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`showtime\` ADD CONSTRAINT \`FK_1af27f8171269552599f8e18ff1\` FOREIGN KEY (\`movieId\`) REFERENCES \`movie\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`showtime\` ADD CONSTRAINT \`FK_c723afd3a25e576a86d90c16d6f\` FOREIGN KEY (\`screenId\`) REFERENCES \`screen\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` ADD CONSTRAINT \`FK_f641f620b3fe496553aa442b026\` FOREIGN KEY (\`genreId\`) REFERENCES \`genre\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` ADD CONSTRAINT \`FK_89ab58f5defce509fa9acffa723\` FOREIGN KEY (\`movieId\`) REFERENCES \`movie\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_1337f93918c70837d3cea105d39\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_4ccf71f9d14aa1a059877b06343\` FOREIGN KEY (\`movieId\`) REFERENCES \`movie\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_88ff32ea732221f2c9ed3818908\` FOREIGN KEY (\`groupRoleId\`) REFERENCES \`group_role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_88ff32ea732221f2c9ed3818908\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_4ccf71f9d14aa1a059877b06343\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_1337f93918c70837d3cea105d39\``);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` DROP FOREIGN KEY \`FK_89ab58f5defce509fa9acffa723\``);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` DROP FOREIGN KEY \`FK_f641f620b3fe496553aa442b026\``);
        await queryRunner.query(`ALTER TABLE \`showtime\` DROP FOREIGN KEY \`FK_c723afd3a25e576a86d90c16d6f\``);
        await queryRunner.query(`ALTER TABLE \`showtime\` DROP FOREIGN KEY \`FK_1af27f8171269552599f8e18ff1\``);
        await queryRunner.query(`ALTER TABLE \`screen\` DROP FOREIGN KEY \`FK_251c9d2385c1ddcc67bb2e718e6\``);
        await queryRunner.query(`ALTER TABLE \`seat\` DROP FOREIGN KEY \`FK_1140d3d30847c3a13faa0a43329\``);
        await queryRunner.query(`ALTER TABLE \`ticket\` DROP FOREIGN KEY \`FK_4931e2f03f0800846072cda2daf\``);
        await queryRunner.query(`ALTER TABLE \`ticket\` DROP FOREIGN KEY \`FK_ab9b02f72bbc7d05bd15a5cb6b4\``);
        await queryRunner.query(`ALTER TABLE \`ticket\` DROP FOREIGN KEY \`FK_2c35aa6c90c4dd7450dad753ae5\``);
        await queryRunner.query(`ALTER TABLE \`bill\` DROP FOREIGN KEY \`FK_275fe11db713fd6f9fd62709917\``);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` DROP FOREIGN KEY \`FK_83ebabf176958d675e0a73892be\``);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` DROP FOREIGN KEY \`FK_542fcdecad4a79dbee3bbe27250\``);
        await queryRunner.query(`DROP INDEX \`review_index\` ON \`review\``);
        await queryRunner.query(`DROP INDEX \`movie_text\` ON \`movie\``);
        await queryRunner.query(`DROP INDEX \`movieGenre_index\` ON \`movie_genre\``);
        await queryRunner.query(`DROP INDEX \`genre_full\` ON \`genre\``);
        await queryRunner.query(`DROP INDEX \`showtime_index\` ON \`showtime\``);
        await queryRunner.query(`DROP INDEX \`ticket_index\` ON \`ticket\``);
        await queryRunner.query(`DROP INDEX \`bill_Index\` ON \`bill\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`groupRoleId\` \`groupRoleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`created_at\` \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone\` \`phone\` varchar(15) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_88ff32ea732221f2c9ed3818908\` FOREIGN KEY (\`groupRoleId\`) REFERENCES \`group_role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` CHANGE \`movieId\` \`movieId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`review\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`review\` CHANGE \`comment\` \`comment\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`review_index\` ON \`review\` (\`rating\`, \`userId\`, \`movieId\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_4ccf71f9d14aa1a059877b06343\` FOREIGN KEY (\`movieId\`) REFERENCES \`movie\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_1337f93918c70837d3cea105d39\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`endDate\` \`endDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`releaseDate\` \`releaseDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`posterUrl\` \`posterUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`trailerUrl\` \`trailerUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`movie\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE FULLTEXT INDEX \`movie_text\` ON \`movie\` (\`title\`, \`description\`)`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` CHANGE \`movieId\` \`movieId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` CHANGE \`genreId\` \`genreId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`movieGenre_index\` ON \`movie_genre\` (\`genreId\`, \`movieId\`)`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` ADD CONSTRAINT \`FK_89ab58f5defce509fa9acffa723\` FOREIGN KEY (\`movieId\`) REFERENCES \`movie\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`movie_genre\` ADD CONSTRAINT \`FK_f641f620b3fe496553aa442b026\` FOREIGN KEY (\`genreId\`) REFERENCES \`genre\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`genre\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE FULLTEXT INDEX \`genre_full\` ON \`genre\` (\`name\`, \`description\`)`);
        await queryRunner.query(`ALTER TABLE \`showtime\` CHANGE \`screenId\` \`screenId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`showtime\` CHANGE \`movieId\` \`movieId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`showtime_index\` ON \`showtime\` (\`movieId\`, \`screenId\`)`);
        await queryRunner.query(`ALTER TABLE \`showtime\` ADD CONSTRAINT \`FK_c723afd3a25e576a86d90c16d6f\` FOREIGN KEY (\`screenId\`) REFERENCES \`screen\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`showtime\` ADD CONSTRAINT \`FK_1af27f8171269552599f8e18ff1\` FOREIGN KEY (\`movieId\`) REFERENCES \`movie\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`screen\` CHANGE \`theaterId\` \`theaterId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`screen\` ADD CONSTRAINT \`FK_251c9d2385c1ddcc67bb2e718e6\` FOREIGN KEY (\`theaterId\`) REFERENCES \`theater\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seat\` CHANGE \`screenId\` \`screenId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`seat\` ADD CONSTRAINT \`FK_1140d3d30847c3a13faa0a43329\` FOREIGN KEY (\`screenId\`) REFERENCES \`screen\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ticket\` CHANGE \`billId\` \`billId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ticket\` CHANGE \`seatId\` \`seatId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ticket\` CHANGE \`showtimeId\` \`showtimeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`ticket_index\` ON \`ticket\` (\`showtimeId\`, \`seatId\`, \`billId\`)`);
        await queryRunner.query(`ALTER TABLE \`ticket\` ADD CONSTRAINT \`FK_4931e2f03f0800846072cda2daf\` FOREIGN KEY (\`billId\`) REFERENCES \`bill\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ticket\` ADD CONSTRAINT \`FK_ab9b02f72bbc7d05bd15a5cb6b4\` FOREIGN KEY (\`seatId\`) REFERENCES \`seat\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ticket\` ADD CONSTRAINT \`FK_2c35aa6c90c4dd7450dad753ae5\` FOREIGN KEY (\`showtimeId\`) REFERENCES \`showtime\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`group_role\` CHANGE \`created_at\` \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`group_role\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` CHANGE \`permissionId\` \`permissionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`group_role_permission\` CHANGE \`groupRoleId\` \`groupRoleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permission\` CHANGE \`created_at\` \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`permission\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bill\` DROP COLUMN \`expiration_time\``);
        await queryRunner.query(`CREATE INDEX \`FK_275fe11db713fd6f9fd62709917\` ON \`bill\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_83ebabf176958d675e0a73892be\` ON \`group_role_permission\` (\`permissionId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_542fcdecad4a79dbee3bbe27250\` ON \`group_role_permission\` (\`groupRoleId\`)`);
    }

}
